---
- name: "Register daemon /etc/systemd/system/{{ zookeeper.daemon.name }}"
  template: src=daemon_systemctl.j2 dest=/etc/systemd/system/{{ zookeeper.daemon.name }}.service
  tags: deploy

- name: chown & chmod daemon /etc/systemd/system/{{ zookeeper.daemon.name }}
  file:
    path: /etc/systemd/system/{{ zookeeper.daemon.name }}.service
    state: file
    owner: root
    group: root
    mode: "0777"

- name: Reload, enable and start daemon
  command: "{{ item }}"
  with_items:
    - systemctl daemon-reload
    - systemctl enable {{ zookeeper.daemon.name }}
    - systemctl start {{ zookeeper.daemon.name }}
